name: push

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        alpine_ver: [latest]
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: vsaps/maven
  update-readme:
    runs-on: ubuntu-latest
    needs: push
    steps:
      - uses: actions/checkout@v3
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3.4.2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: vsaps/maven
          short-description: ${{ github.event.repository.description }}
